name: Bug
description: Report a bug in Oqix bot
title: "Bug: "
labels: ["bug"]
body:
  - type: dropdown
    id: severity
    attributes:
      description: "Please select severity of the bug"
      label: severity-bug
      options:
        - critical
        - major
        - minor
        - trivial
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      description: "Please add information about your bug"
      label: description-bug
    validations:
      required: true
