name: Feature request
description: Request new feature to Oqix bot
title: "Feature request: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      description: "Please add information about your new feature"
      label: Description of the feature
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      description: "Please add related links if any"
      label: Related links
