name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]

jobs:
  new-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Comment to PR and add labels"
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var comment = "Hello 👋, thank you for opening new PR to OqixTS 💗\n\n Please, wait till somebody will review your PR.\n"
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
      - name: Add review-needed label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: review-needed
