name: Pull request workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
