name: Pull request workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/build
      - name: Test
        uses: ./.github/actions/test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        uses: ./.github/actions/build
      - name: Lint project
        uses: ./.github/actions/lint
  test-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test build image
        shell: bash
        run: |
          docker buildx create --name oqixBuilder --use
          docker buildx build --platform linux/arm64 -t mimotej/oqix:$GITHUB_SHA -t mimotej/oqix:latest .
